# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# ----------------------------------------------------------------------------------------------------------------
# -------------------
# Seo stuff
# -------------------

title: Salvador Aleguas
tagline: Developer portfolio website of Salvador Aleguas
email: salvador@aleguas.dev
description: >- # this means to ignore newlines until "baseurl:"
  Hey! I'm a highly motivated open-source developer and writer who is passionate about anything computer related.
  I specalize in Python, Data Science, and documentation. I also enjoy other computer-related topics, , such as
  Cybersecurity and Databases. I'm currently a Junior in High School!

author: Salvador Aleguas
logo: /img/logo_large.png
social:
  name: Salvador Aleguas
  links:
    - https://medium.com/@salvadoraleguas
    - https://github.com/saleguas
# -------------------
# End Seo stuff
# -------------------


# -------------------
# Other site stuff
# -------------------
location: Fort Lauderdale, Florida

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aleguas.dev" # the base hostname & protocol for your site, e.g. http://example.com

# -------------------
# End other site stuff
# -------------------

# -------------------
# Plugin stuff
# -------------------
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

webmaster_verifications:
  yandex: 6418d2cf59c4ecb5
# -------------------
# End Plugin stuff
# -------------------
